/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => IDEStylePreviewPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

// node_modules/monkey-around/dist/index.mjs
function around(obj, factories) {
  const removers = Object.keys(factories).map((key) => around1(obj, key, factories[key]));
  return removers.length === 1 ? removers[0] : function() {
    removers.forEach((r) => r());
  };
}
function around1(obj, method, createWrapper) {
  const inherited = obj[method], hadOwn = obj.hasOwnProperty(method), original = hadOwn ? inherited : function() {
    return Object.getPrototypeOf(obj)[method].apply(this, arguments);
  };
  let current = createWrapper(original);
  if (inherited)
    Object.setPrototypeOf(current, inherited);
  Object.setPrototypeOf(wrapper, current);
  obj[method] = wrapper;
  return remove;
  function wrapper(...args) {
    if (current === original && obj[method] === wrapper)
      remove();
    return current.apply(this, args);
  }
  function remove() {
    if (obj[method] === wrapper) {
      if (hadOwn)
        obj[method] = original;
      else
        delete obj[method];
    }
    if (current === original)
      return;
    current = original;
    Object.setPrototypeOf(wrapper, inherited || Function);
  }
}

// main.ts
var CONFIG = {
  /** Debounce delay for inline title rename / 인라인 제목 변경 시 파일명 반영 대기 시간 */
  TITLE_RENAME_DEBOUNCE_MS: 300,
  /** Min pixel distance to distinguish drag from click in graph view / 그래프뷰에서 드래그와 클릭을 구분하는 최소 px 거리 */
  GRAPH_DRAG_THRESHOLD: 10,
  VIEW_TYPES: {
    EMPTY: "empty",
    MARKDOWN: "markdown",
    CANVAS: "canvas",
    PDF: "pdf",
    GRAPH: "graph",
    FILE_EXPLORER: "file-explorer"
  },
  CSS_CLASSES: {
    PREVIEW_TAB: "is-preview-tab"
  },
  CSS_SELECTORS: {
    TAB_HEADER: ".workspace-tab-header",
    LEAF_CONTENT: ".workspace-leaf-content",
    GRAPH_CONTAINER: ".graph-view-container",
    RIBBON_ACTION: ".side-dock-ribbon-action",
    INLINE_TITLE: ".inline-title",
    STALE_ACTIVE: ".tree-item-self.is-active",
    STALE_FOCUS: ".tree-item-self.has-focus"
  },
  LOG_PREFIX: "[IDE Preview]"
};
function log(message, ...args) {
  console.debug(`${CONFIG.LOG_PREFIX} ${message}`, ...args);
}
var IDEStylePreviewPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    // ─────────────────────────────────────────────────────────────────────────
    // State / 상태
    // ─────────────────────────────────────────────────────────────────────────
    /** Leaves currently in preview state / Preview 상태인 탭들 */
    this.previewLeaves = /* @__PURE__ */ new WeakSet();
    /** Leaves already handled by openFile (prevents setViewState double-processing) */
    /** openFile에서 이미 처리한 탭 (setViewState 중복 방지) */
    this.processedByOpenFile = /* @__PURE__ */ new WeakSet();
    /** Ctrl/Cmd+Click detection flag / Ctrl+Click 감지 플래그 */
    this.isCtrlClickPending = false;
    /** Expected view type for ribbon double-click promotion (null = inactive) */
    /** 리본 버튼 더블클릭 시 기대하는 뷰 타입 (null이면 비활성) */
    this.ribbonDoubleClickExpectedViewType = null;
    /** Graph view drag detection / 그래프 뷰 드래그 감지용 */
    this.graphDragStartPos = null;
    /** Newly created files awaiting title-edit mode / 새로 생성된 파일들 (제목편집모드 통일용) */
    this.newlyCreatedFiles = /* @__PURE__ */ new Set();
    /** Most recently opened leaf (for double-click promotion in sidebar/graph) */
    /** 가장 최근에 열린 leaf (사이드바/그래프 더블클릭 승격 시 사용) */
    this.lastActiveLeaf = null;
    /** Inline title rename debounce timer / 제목 변경 debounce 타이머 */
    this.titleRenameTimer = null;
    /** Patch cleanup functions / 패치 해제 함수들 */
    this.cleanupFunctions = [];
  }
  // ─────────────────────────────────────────────────────────────────────────
  // Lifecycle / 라이프사이클
  // ─────────────────────────────────────────────────────────────────────────
  onload() {
    log("Plugin loaded");
    this.installPatches();
    this.registerEventHandlers();
  }
  onunload() {
    this.cleanupFunctions.forEach((cleanup) => cleanup());
    this.cleanupFunctions = [];
    this.removeAllPreviewStyles();
    log("Plugin unloaded");
  }
  // ─────────────────────────────────────────────────────────────────────────
  // Patch Installation / 패치 설치
  // ─────────────────────────────────────────────────────────────────────────
  installPatches() {
    this.patchOpenFile();
    this.patchSetViewState();
    this.patchDetach();
    this.patchSetPinned();
    this.patchVaultCreate();
  }
  registerEventHandlers() {
    this.registerFileOpenHandler();
    this.registerClickHandlers();
    this.registerPromotionTriggers();
  }
  // ─────────────────────────────────────────────────────────────────────────
  // Tab State Management / 탭 상태 관리
  // ─────────────────────────────────────────────────────────────────────────
  getTabState(leaf) {
    var _a;
    if (((_a = leaf.view) == null ? void 0 : _a.getViewType()) === CONFIG.VIEW_TYPES.EMPTY)
      return "empty";
    if (this.previewLeaves.has(leaf))
      return "preview";
    return "permanent";
  }
  setAsPreview(leaf) {
    this.previewLeaves.add(leaf);
    this.updateTabStyle(leaf);
  }
  setAsPermanent(leaf) {
    this.previewLeaves.delete(leaf);
    this.updateTabStyle(leaf);
  }
  promoteToPermanent(leaf) {
    if (!this.previewLeaves.has(leaf))
      return;
    this.setAsPermanent(leaf);
    log("Promoted to permanent:", this.getLeafId(leaf));
  }
  // ─────────────────────────────────────────────────────────────────────────
  // Location / 위치 판단
  // ─────────────────────────────────────────────────────────────────────────
  getLeafLocation(leaf) {
    const workspace = this.app.workspace;
    const root = leaf.getRoot();
    if (root === workspace.leftSplit || root === workspace.rightSplit) {
      return "sidebar";
    }
    return "main";
  }
  isInSidebar(leaf) {
    return this.getLeafLocation(leaf) === "sidebar";
  }
  // ─────────────────────────────────────────────────────────────────────────
  // Intent Detection / 의도 판별
  // ─────────────────────────────────────────────────────────────────────────
  /**
   * Determine file open intent: browse (view) or create (new file).
   * 파일 열기 의도 판별: 탐색(조회) 또는 생성(새 파일).
   */
  determineOpenIntent(file, openState) {
    var _a, _b;
    if (((_a = openState == null ? void 0 : openState.eState) == null ? void 0 : _a.rename) === "all") {
      return "create";
    }
    if (file.extension === CONFIG.VIEW_TYPES.CANVAS || file.extension === CONFIG.VIEW_TYPES.PDF) {
      return "browse";
    }
    if (((_b = openState == null ? void 0 : openState.state) == null ? void 0 : _b.mode) === "source") {
      if (this.isDailyNote(file)) {
        return "create";
      }
    }
    return "browse";
  }
  // ─────────────────────────────────────────────────────────────────────────
  // Leaf Search / Leaf 탐색
  // ─────────────────────────────────────────────────────────────────────────
  findLeafWithFile(filePath, inSameGroupAs) {
    const siblings = this.getSiblingLeaves(inSameGroupAs);
    for (const sibling of siblings) {
      if (this.getFilePath(sibling) === filePath) {
        return sibling;
      }
    }
    return null;
  }
  findLeafWithViewType(viewType, inSameGroupAs) {
    var _a;
    const siblings = this.getSiblingLeaves(inSameGroupAs);
    for (const sibling of siblings) {
      if (((_a = sibling.view) == null ? void 0 : _a.getViewType()) === viewType) {
        return sibling;
      }
    }
    return null;
  }
  findPreviewLeaf(inSameGroupAs) {
    const siblings = this.getSiblingLeaves(inSameGroupAs);
    for (const sibling of siblings) {
      if (this.previewLeaves.has(sibling)) {
        return sibling;
      }
    }
    return null;
  }
  getSiblingLeaves(leaf) {
    var _a;
    const internal = leaf;
    const children = (_a = internal.parent) == null ? void 0 : _a.children;
    if (!children)
      return [];
    return children.filter((child) => child !== leaf);
  }
  // ─────────────────────────────────────────────────────────────────────────
  // openFile Patch / openFile 패치
  // ─────────────────────────────────────────────────────────────────────────
  patchOpenFile() {
    const boundHandler = this.handleOpenFile.bind(this);
    const uninstall = around(import_obsidian.WorkspaceLeaf.prototype, {
      openFile(original) {
        return async function(file, openState) {
          return boundHandler(this, file, openState, original);
        };
      }
    });
    this.cleanupFunctions.push(uninstall);
    log("Patched openFile");
  }
  /**
   * Core open-file handler. Decides Preview vs Permanent based on intent.
   * 핵심 파일 열기 핸들러. 의도에 따라 Preview/Permanent를 결정합니다.
   *
   * Flow / 흐름:
   * 1. Apply rename mode for newly created files / 새 파일에 제목편집모드 적용
   * 2. Skip if same file already open / 같은 파일이면 무시
   * 3. Focus existing tab if duplicate / 중복 시 기존 탭 포커스
   * 4. Permanent: create/ctrl-click → new tab / Permanent: 생성/Ctrl클릭 → 새 탭
   * 5. Preview: reuse existing preview tab / Preview: 기존 Preview 탭 재사용
   * 6. Fallback: use current tab / 폴백: 현재 탭 사용
   */
  async handleOpenFile(leaf, file, openState, originalMethod) {
    var _a;
    if (this.newlyCreatedFiles.has(file.path)) {
      this.newlyCreatedFiles.delete(file.path);
      if (!this.isDailyNote(file)) {
        openState = openState != null ? openState : {};
        openState.eState = (_a = openState.eState) != null ? _a : {};
        openState.eState.rename = "all";
      }
    }
    const currentState = this.getTabState(leaf);
    const intent = this.determineOpenIntent(file, openState);
    const isCtrlClick = this.consumeCtrlClickFlag();
    const shouldBePermanent = intent === "create" || isCtrlClick;
    if (this.getFilePath(leaf) === file.path) {
      return;
    }
    const existingLeaf = this.findLeafWithFile(file.path, leaf);
    if (existingLeaf && !isCtrlClick) {
      this.app.workspace.setActiveLeaf(existingLeaf, { focus: true });
      return;
    }
    if (shouldBePermanent) {
      if (currentState === "permanent" || currentState === "preview") {
        return await this.openInNewTab(file, openState, true, originalMethod);
      }
      this.markAsProcessed(leaf);
      const result2 = await originalMethod.call(leaf, file, openState);
      this.setAsPermanent(leaf);
      return result2;
    }
    const existingPreview = this.findPreviewLeaf(leaf);
    if (existingPreview) {
      this.markAsProcessed(existingPreview);
      const result2 = await originalMethod.call(existingPreview, file, openState);
      this.app.workspace.setActiveLeaf(existingPreview, { focus: true });
      return result2;
    }
    if (currentState === "permanent") {
      return await this.openInNewTab(file, openState, false, originalMethod);
    }
    this.markAsProcessed(leaf);
    const result = await originalMethod.call(leaf, file, openState);
    this.setAsPreview(leaf);
    this.ensureExplorerActiveState(file);
    return result;
  }
  async openInNewTab(file, openState, asPermanent, originalMethod) {
    var _a;
    const shouldApplyRename = ((_a = openState == null ? void 0 : openState.eState) == null ? void 0 : _a.rename) === "all";
    const newLeaf = this.app.workspace.getLeaf("tab");
    this.markAsProcessed(newLeaf);
    const result = await originalMethod.call(newLeaf, file, openState);
    if (asPermanent) {
      this.setAsPermanent(newLeaf);
    } else {
      this.setAsPreview(newLeaf);
    }
    this.app.workspace.setActiveLeaf(newLeaf, { focus: true });
    if (shouldApplyRename) {
      this.applyRenameMode(newLeaf);
    }
    return result;
  }
  applyRenameMode(leaf) {
    const view = leaf.view;
    if (view == null ? void 0 : view.setEphemeralState) {
      view.setEphemeralState({ rename: "all" });
    }
  }
  // ─────────────────────────────────────────────────────────────────────────
  // setViewState Patch (non-file views) / setViewState 패치 (비파일 뷰 처리)
  // ─────────────────────────────────────────────────────────────────────────
  patchSetViewState() {
    const boundHandler = this.handleSetViewState.bind(this);
    const uninstall = around(import_obsidian.WorkspaceLeaf.prototype, {
      setViewState(original) {
        return async function(viewState, eState) {
          return boundHandler(this, viewState, eState, original);
        };
      }
    });
    this.cleanupFunctions.push(uninstall);
    log("Patched setViewState");
  }
  /**
   * Handle non-file views (Graph, Canvas, etc.) with same Preview/Permanent logic.
   * 비파일 뷰(Graph, Canvas 등)를 동일한 Preview/Permanent 로직으로 처리합니다.
   *
   * processedByOpenFile flag: when openFile already handled this leaf,
   * skip our logic and pass through to original setViewState.
   * processedByOpenFile 플래그: openFile에서 이미 처리한 경우 원본 setViewState로 통과.
   */
  async handleSetViewState(leaf, viewState, eState, originalMethod) {
    var _a;
    if (this.wasProcessed(leaf)) {
      this.clearProcessed(leaf);
      return originalMethod.call(leaf, viewState, eState);
    }
    const viewType = viewState == null ? void 0 : viewState.type;
    if (viewType === CONFIG.VIEW_TYPES.MARKDOWN || viewType === CONFIG.VIEW_TYPES.EMPTY) {
      return originalMethod.call(leaf, viewState, eState);
    }
    if (this.isInSidebar(leaf)) {
      return originalMethod.call(leaf, viewState, eState);
    }
    const currentState = this.getTabState(leaf);
    const shouldBePermanent = this.consumeRibbonDoubleClickFlag(viewType);
    if (((_a = leaf.view) == null ? void 0 : _a.getViewType()) === viewType) {
      if (shouldBePermanent && this.previewLeaves.has(leaf)) {
        this.promoteToPermanent(leaf);
      }
      return;
    }
    const existingLeaf = this.findLeafWithViewType(viewType, leaf);
    if (existingLeaf) {
      if (shouldBePermanent && this.previewLeaves.has(existingLeaf)) {
        this.promoteToPermanent(existingLeaf);
      }
      this.app.workspace.setActiveLeaf(existingLeaf, { focus: true });
      return;
    }
    if (shouldBePermanent) {
      if (currentState === "permanent" || currentState === "preview") {
        const newLeaf = this.app.workspace.getLeaf("tab");
        const result3 = await originalMethod.call(newLeaf, viewState, eState);
        this.setAsPermanent(newLeaf);
        this.app.workspace.setActiveLeaf(newLeaf, { focus: true });
        return result3;
      }
      const result2 = await originalMethod.call(leaf, viewState, eState);
      this.setAsPermanent(leaf);
      return result2;
    }
    const existingPreview = this.findPreviewLeaf(leaf);
    if (existingPreview) {
      const result2 = await originalMethod.call(existingPreview, viewState, eState);
      this.app.workspace.setActiveLeaf(existingPreview, { focus: true });
      return result2;
    }
    if (currentState === "permanent") {
      const newLeaf = this.app.workspace.getLeaf("tab");
      const result2 = await originalMethod.call(newLeaf, viewState, eState);
      this.setAsPreview(newLeaf);
      this.app.workspace.setActiveLeaf(newLeaf, { focus: true });
      return result2;
    }
    const result = await originalMethod.call(leaf, viewState, eState);
    this.setAsPreview(leaf);
    return result;
  }
  // ─────────────────────────────────────────────────────────────────────────
  // detach Patch (tab close cleanup) / detach 패치 (탭 닫힘 처리)
  // ─────────────────────────────────────────────────────────────────────────
  /**
   * Two-phase sidebar cleanup on tab close:
   * 탭 닫힘 시 2단계 사이드바 정리:
   *
   * Phase 1 (before detach): Reset internal state via onFileOpen(null)
   *   detach 전: onFileOpen(null)로 내부 상태 리셋
   * Phase 2 (after detach, async): Clean stale DOM classes
   *   detach 후(비동기): 잔류 DOM 클래스 정리
   */
  patchDetach() {
    const clearState = this.clearSidebarInternalState.bind(this);
    const cleanDOM = this.cleanStaleSidebarDOM.bind(this);
    const uninstall = around(import_obsidian.WorkspaceLeaf.prototype, {
      detach(original) {
        return function() {
          clearState();
          const result = original.call(this);
          setTimeout(() => cleanDOM(), 0);
          return result;
        };
      }
    });
    this.cleanupFunctions.push(uninstall);
    log("Patched detach");
  }
  // ─────────────────────────────────────────────────────────────────────────
  // setPinned Patch (pin → promote) / setPinned 패치 (탭 고정 시 승격)
  // ─────────────────────────────────────────────────────────────────────────
  patchSetPinned() {
    const { previewLeaves } = this;
    const promote = this.promoteToPermanent.bind(this);
    const uninstall = around(import_obsidian.WorkspaceLeaf.prototype, {
      setPinned(original) {
        return function(pinned) {
          if (pinned && previewLeaves.has(this)) {
            promote(this);
          }
          return original.call(this, pinned);
        };
      }
    });
    this.cleanupFunctions.push(uninstall);
    log("Patched setPinned");
  }
  // ─────────────────────────────────────────────────────────────────────────
  // vault.create Patch (new file detection) / vault.create 패치 (새 파일 생성 감지)
  // ─────────────────────────────────────────────────────────────────────────
  patchVaultCreate() {
    const { newlyCreatedFiles } = this;
    const vault = this.app.vault;
    const originalCreate = vault.create.bind(vault);
    vault.create = function(path, data, options) {
      newlyCreatedFiles.add(path);
      return originalCreate(path, data, options);
    };
    this.cleanupFunctions.push(() => {
      vault.create = originalCreate;
    });
    log("Patched vault.create");
  }
  // ─────────────────────────────────────────────────────────────────────────
  // Event Handlers / 이벤트 핸들러
  // ─────────────────────────────────────────────────────────────────────────
  registerFileOpenHandler() {
    this.registerEvent(
      this.app.workspace.on("file-open", (file) => {
        var _a;
        if (!file)
          return;
        const activeLeaf = this.getActiveLeaf();
        const viewType = (_a = activeLeaf == null ? void 0 : activeLeaf.view) == null ? void 0 : _a.getViewType();
        if (viewType === CONFIG.VIEW_TYPES.MARKDOWN || viewType === CONFIG.VIEW_TYPES.CANVAS || viewType === CONFIG.VIEW_TYPES.PDF) {
          this.lastActiveLeaf = activeLeaf;
        }
      })
    );
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", (leaf) => {
        var _a;
        if (!this.ribbonDoubleClickExpectedViewType || !leaf) {
          return;
        }
        const viewType = (_a = leaf.view) == null ? void 0 : _a.getViewType();
        const expectedType = this.ribbonDoubleClickExpectedViewType;
        if (viewType === expectedType && this.previewLeaves.has(leaf)) {
          this.promoteToPermanent(leaf);
        }
        this.ribbonDoubleClickExpectedViewType = null;
      })
    );
  }
  registerClickHandlers() {
    this.registerDomEvent(document, "mousedown", (evt) => {
      if ((evt.ctrlKey || evt.metaKey) && this.isFileElement(evt.target)) {
        this.isCtrlClickPending = true;
      }
    }, true);
    this.registerDomEvent(document, "dblclick", (evt) => {
      this.handleDoubleClick(evt);
    }, true);
    this.registerDomEvent(document, "mousedown", (evt) => {
      var _a;
      const activeLeaf = this.getActiveLeaf();
      if (((_a = activeLeaf == null ? void 0 : activeLeaf.view) == null ? void 0 : _a.getViewType()) === CONFIG.VIEW_TYPES.GRAPH) {
        this.graphDragStartPos = { x: evt.clientX, y: evt.clientY };
      }
    }, true);
    this.registerDomEvent(document, "mouseup", (evt) => {
      var _a;
      if (!this.graphDragStartPos)
        return;
      const activeLeaf = this.getActiveLeaf();
      if (((_a = activeLeaf == null ? void 0 : activeLeaf.view) == null ? void 0 : _a.getViewType()) === CONFIG.VIEW_TYPES.GRAPH) {
        const dx = evt.clientX - this.graphDragStartPos.x;
        const dy = evt.clientY - this.graphDragStartPos.y;
        const distance = Math.sqrt(dx * dx + dy * dy);
        if (distance > CONFIG.GRAPH_DRAG_THRESHOLD && activeLeaf && this.previewLeaves.has(activeLeaf)) {
          this.promoteToPermanent(activeLeaf);
        }
      }
      this.graphDragStartPos = null;
    }, true);
  }
  /**
   * Handle double-click across different UI regions.
   * 다양한 UI 영역의 더블클릭을 처리합니다.
   *
   * Tab header: promotes activeLeaf directly / 탭 헤더: activeLeaf를 직접 승격
   * Sidebar/Graph: promotes lastActiveLeaf (set by file-open event)
   * 사이드바/그래프: lastActiveLeaf를 승격 (file-open 이벤트에서 설정됨)
   */
  handleDoubleClick(evt) {
    const target = evt.target;
    if (target.closest(CONFIG.CSS_SELECTORS.TAB_HEADER)) {
      const activeLeaf = this.getActiveLeaf();
      if (activeLeaf && this.previewLeaves.has(activeLeaf)) {
        this.promoteToPermanent(activeLeaf);
      }
      return;
    }
    const sidebarContent = target.closest(CONFIG.CSS_SELECTORS.LEAF_CONTENT);
    if (sidebarContent) {
      const leaf = this.findLeafByContentEl(sidebarContent);
      if (leaf && this.isInSidebar(leaf)) {
        if (this.lastActiveLeaf && this.previewLeaves.has(this.lastActiveLeaf)) {
          this.promoteToPermanent(this.lastActiveLeaf);
        }
        return;
      }
    }
    if (target.closest(CONFIG.CSS_SELECTORS.GRAPH_CONTAINER)) {
      if (this.lastActiveLeaf && this.previewLeaves.has(this.lastActiveLeaf)) {
        this.promoteToPermanent(this.lastActiveLeaf);
      }
      return;
    }
    const ribbonButton = target.closest(CONFIG.CSS_SELECTORS.RIBBON_ACTION);
    if (ribbonButton) {
      this.handleRibbonDoubleClick(ribbonButton);
    }
  }
  /**
   * Ribbon double-click: promote current preview or set flag for pending view.
   * 리본 더블클릭: 현재 Preview를 승격하거나, 아직 열리지 않은 뷰를 위해 플래그 설정.
   */
  handleRibbonDoubleClick(ribbonButton) {
    var _a, _b;
    const ariaLabel = (_a = ribbonButton.getAttribute("aria-label")) != null ? _a : "";
    const activeLeaf = this.getActiveLeaf();
    if (activeLeaf && this.previewLeaves.has(activeLeaf)) {
      this.promoteToPermanent(activeLeaf);
      return;
    }
    const ariaLower = ariaLabel.toLowerCase();
    let viewType = null;
    if (ariaLower.includes("graph") || ariaLabel.includes("\uADF8\uB798\uD504")) {
      viewType = CONFIG.VIEW_TYPES.GRAPH;
    } else if (ariaLower.includes("canvas") || ariaLabel.includes("\uCE94\uBC84\uC2A4")) {
      viewType = CONFIG.VIEW_TYPES.CANVAS;
    }
    if (viewType) {
      const currentActiveLeaf = this.getActiveLeaf();
      if (((_b = currentActiveLeaf == null ? void 0 : currentActiveLeaf.view) == null ? void 0 : _b.getViewType()) === viewType && this.previewLeaves.has(currentActiveLeaf)) {
        this.promoteToPermanent(currentActiveLeaf);
        return;
      }
    }
    if (viewType) {
      this.ribbonDoubleClickExpectedViewType = viewType;
    }
  }
  // ─────────────────────────────────────────────────────────────────────────
  // Promotion Triggers / 승격 트리거
  // ─────────────────────────────────────────────────────────────────────────
  registerPromotionTriggers() {
    this.registerEvent(
      this.app.workspace.on("editor-change", (editor, info) => {
        const leaf = info.leaf;
        if (leaf && this.previewLeaves.has(leaf)) {
          this.promoteToPermanent(leaf);
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("rename", (file, oldPath) => {
        this.app.workspace.iterateAllLeaves((leaf) => {
          if (this.getFilePath(leaf) === file.path && this.previewLeaves.has(leaf)) {
            this.promoteToPermanent(leaf);
          }
        });
      })
    );
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (!(file instanceof import_obsidian.TFile))
          return;
        if (file.extension !== CONFIG.VIEW_TYPES.CANVAS)
          return;
        this.app.workspace.iterateAllLeaves((leaf) => {
          if (this.getFilePath(leaf) === file.path && this.previewLeaves.has(leaf)) {
            this.promoteToPermanent(leaf);
          }
        });
      })
    );
    this.registerDomEvent(document, "input", (evt) => {
      this.handleInlineTitleEdit(evt);
    }, true);
  }
  handleInlineTitleEdit(evt) {
    var _a, _b;
    const target = evt.target;
    if (!target.classList.contains(CONFIG.CSS_SELECTORS.INLINE_TITLE.slice(1)))
      return;
    const activeLeaf = this.getActiveLeaf();
    if (!activeLeaf)
      return;
    if (this.previewLeaves.has(activeLeaf)) {
      this.promoteToPermanent(activeLeaf);
    }
    this.scheduleFileRename(activeLeaf, (_b = (_a = target.textContent) == null ? void 0 : _a.trim()) != null ? _b : "");
  }
  scheduleFileRename(leaf, newTitle) {
    const currentPath = this.getFilePath(leaf);
    if (!currentPath || !newTitle)
      return;
    if (this.titleRenameTimer) {
      window.clearTimeout(this.titleRenameTimer);
    }
    this.titleRenameTimer = window.setTimeout(() => {
      void this.renameFile(currentPath, newTitle);
    }, CONFIG.TITLE_RENAME_DEBOUNCE_MS);
  }
  async renameFile(currentPath, newTitle) {
    var _a, _b;
    const file = this.app.vault.getAbstractFileByPath(currentPath);
    if (!(file instanceof import_obsidian.TFile))
      return;
    const folder = (_b = (_a = file.parent) == null ? void 0 : _a.path) != null ? _b : "";
    const newPath = folder ? `${folder}/${newTitle}.md` : `${newTitle}.md`;
    if (newPath === currentPath)
      return;
    try {
      log(`Renaming: ${currentPath} \u2192 ${newPath}`);
      await this.app.fileManager.renameFile(file, newPath);
    } catch (e) {
      const message = e instanceof Error ? e.message : String(e);
      log(`Rename failed: ${message}`);
      new import_obsidian.Notice(`\uD30C\uC77C\uBA85 \uBCC0\uACBD \uC2E4\uD328: ${message}`);
    }
  }
  // ─────────────────────────────────────────────────────────────────────────
  // Tab Style / 탭 스타일
  // ─────────────────────────────────────────────────────────────────────────
  updateTabStyle(leaf) {
    const tabHeaderEl = leaf.tabHeaderEl;
    if (!tabHeaderEl)
      return;
    if (this.previewLeaves.has(leaf)) {
      tabHeaderEl.classList.add(CONFIG.CSS_CLASSES.PREVIEW_TAB);
    } else {
      tabHeaderEl.classList.remove(CONFIG.CSS_CLASSES.PREVIEW_TAB);
    }
  }
  removeAllPreviewStyles() {
    this.app.workspace.iterateAllLeaves((leaf) => {
      const tabHeaderEl = leaf.tabHeaderEl;
      tabHeaderEl == null ? void 0 : tabHeaderEl.classList.remove(CONFIG.CSS_CLASSES.PREVIEW_TAB);
    });
  }
  // ─────────────────────────────────────────────────────────────────────────
  // Sidebar State Management / 사이드바 상태 관리
  // ─────────────────────────────────────────────────────────────────────────
  /**
   * Get file explorer view instance (shared helper for sidebar methods).
   * 파일 탐색기 뷰 인스턴스 획득 (사이드바 메서드 공용 헬퍼).
   */
  getExplorerView() {
    var _a;
    const view = (_a = this.app.workspace.getLeavesOfType(CONFIG.VIEW_TYPES.FILE_EXPLORER)[0]) == null ? void 0 : _a.view;
    return view != null ? view : null;
  }
  /**
   * Phase 1: Reset sidebar internal state before detach.
   * 1단계: detach 전 사이드바 내부 상태 리셋.
   *
   * Without this, re-clicking the same file after closing its tab does nothing
   * because the explorer thinks the file is still active.
   * 이 처리 없이 탭을 닫고 같은 파일을 다시 클릭하면 탐색기가 여전히 활성으로 인식하여 반응 없음.
   */
  clearSidebarInternalState() {
    var _a;
    const explorerView = this.getExplorerView();
    if (!explorerView)
      return;
    if (explorerView.onFileOpen) {
      explorerView.onFileOpen(null);
    }
    if (explorerView.tree && explorerView.tree.activeDom !== null) {
      explorerView.tree.activeDom = null;
    }
    if ((_a = explorerView.tree) == null ? void 0 : _a.setFocusedItem) {
      explorerView.tree.setFocusedItem(null);
    }
  }
  /**
   * Phase 2: Clean stale DOM classes after detach (called via setTimeout).
   * 2단계: detach 후 잔류 DOM 클래스 정리 (setTimeout으로 호출).
   *
   * Obsidian events may restore is-active/has-focus after our Phase 1 cleanup.
   * We compare against internal state and remove any mismatched DOM classes.
   * Obsidian 이벤트가 Phase 1 정리 후 is-active/has-focus를 복원할 수 있음.
   * 내부 상태와 비교하여 불일치하는 DOM 클래스를 제거.
   */
  cleanStaleSidebarDOM() {
    var _a, _b, _c, _d;
    const explorerView = this.getExplorerView();
    if (!explorerView)
      return;
    if (!explorerView.activeDom && !((_a = explorerView.tree) == null ? void 0 : _a.activeDom)) {
      const staleActive = (_b = explorerView.containerEl) == null ? void 0 : _b.querySelectorAll(CONFIG.CSS_SELECTORS.STALE_ACTIVE);
      staleActive == null ? void 0 : staleActive.forEach((el) => el.classList.remove("is-active"));
    }
    if (!((_c = explorerView.tree) == null ? void 0 : _c.focusedItem)) {
      const staleFocus = (_d = explorerView.containerEl) == null ? void 0 : _d.querySelectorAll(CONFIG.CSS_SELECTORS.STALE_FOCUS);
      staleFocus == null ? void 0 : staleFocus.forEach((el) => el.classList.remove("has-focus"));
    }
  }
  /**
   * Safety net: ensure explorer active state after opening a file.
   * 안전망: 파일을 연 뒤 탐색기의 활성 상태가 올바른지 확인.
   *
   * When file-open event doesn't fire (e.g., after detach+reopen),
   * the explorer's activeDom gets out of sync. This forces a re-sync.
   * file-open 이벤트가 발생하지 않는 경우(detach 후 재열기 등)
   * 탐색기의 activeDom이 동기화되지 않으므로 강제 재동기화.
   */
  ensureExplorerActiveState(file) {
    var _a, _b;
    const explorerView = this.getExplorerView();
    if (!(explorerView == null ? void 0 : explorerView.onFileOpen))
      return;
    if (((_b = (_a = explorerView.activeDom) == null ? void 0 : _a.file) == null ? void 0 : _b.path) === file.path) {
      return;
    }
    explorerView.onFileOpen(file);
  }
  // ─────────────────────────────────────────────────────────────────────────
  // Utilities / 유틸리티
  // ─────────────────────────────────────────────────────────────────────────
  getFilePath(leaf) {
    const view = leaf.view;
    if (view instanceof import_obsidian.FileView && view.file) {
      return view.file.path;
    }
    return null;
  }
  getLeafId(leaf) {
    var _a;
    return (_a = leaf.id) != null ? _a : "unknown";
  }
  getActiveLeaf() {
    return this.app.workspace.getMostRecentLeaf();
  }
  isFileElement(target) {
    if (!(target instanceof HTMLElement))
      return false;
    return !!target.closest("[data-path]") || !!target.closest(".tree-item-self");
  }
  /**
   * Detect Daily Notes by checking the internal plugin settings and strict date parsing.
   * Daily Notes 내부 플러그인 설정과 엄격한 날짜 파싱으로 Daily Note 여부를 감지합니다.
   */
  isDailyNote(file) {
    var _a, _b, _c, _d;
    if (file.extension !== "md")
      return false;
    const dailyNotes = (_b = (_a = this.app.internalPlugins) == null ? void 0 : _a.getPluginById) == null ? void 0 : _b.call(_a, "daily-notes");
    if (!(dailyNotes == null ? void 0 : dailyNotes.enabled))
      return false;
    const options = (_c = dailyNotes.instance) == null ? void 0 : _c.options;
    const format = (options == null ? void 0 : options.format) || "YYYY-MM-DD";
    const folder = (options == null ? void 0 : options.folder) || "";
    if (folder && ((_d = file.parent) == null ? void 0 : _d.path) !== folder)
      return false;
    return moment(file.basename, format, true).isValid();
  }
  findLeafByContentEl(contentEl) {
    let found = null;
    this.app.workspace.iterateAllLeaves((leaf) => {
      var _a;
      if ((_a = leaf.containerEl) == null ? void 0 : _a.contains(contentEl)) {
        found = leaf;
      }
    });
    return found;
  }
  markAsProcessed(leaf) {
    this.processedByOpenFile.add(leaf);
  }
  wasProcessed(leaf) {
    return this.processedByOpenFile.has(leaf);
  }
  clearProcessed(leaf) {
    this.processedByOpenFile.delete(leaf);
  }
  consumeCtrlClickFlag() {
    if (this.isCtrlClickPending) {
      this.isCtrlClickPending = false;
      return true;
    }
    return false;
  }
  /**
   * Consume-once flag pattern: returns true if viewType matches the expected ribbon
   * double-click type, then clears the flag. Used by setViewState to detect intent.
   * 1회 소비 플래그 패턴: viewType이 리본 더블클릭 기대 타입과 일치하면 true 반환 후
   * 플래그 초기화. setViewState에서 의도 감지에 사용.
   */
  consumeRibbonDoubleClickFlag(viewType) {
    if (this.ribbonDoubleClickExpectedViewType === viewType) {
      this.ribbonDoubleClickExpectedViewType = null;
      return true;
    }
    return false;
  }
};
