/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => IDEStylePreviewPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

// node_modules/monkey-around/dist/index.mjs
function around(obj, factories) {
  const removers = Object.keys(factories).map((key) => around1(obj, key, factories[key]));
  return removers.length === 1 ? removers[0] : function() {
    removers.forEach((r) => r());
  };
}
function around1(obj, method, createWrapper) {
  const inherited = obj[method], hadOwn = obj.hasOwnProperty(method), original = hadOwn ? inherited : function() {
    return Object.getPrototypeOf(obj)[method].apply(this, arguments);
  };
  let current = createWrapper(original);
  if (inherited)
    Object.setPrototypeOf(current, inherited);
  Object.setPrototypeOf(wrapper, current);
  obj[method] = wrapper;
  return remove;
  function wrapper(...args) {
    if (current === original && obj[method] === wrapper)
      remove();
    return current.apply(this, args);
  }
  function remove() {
    if (obj[method] === wrapper) {
      if (hadOwn)
        obj[method] = original;
      else
        delete obj[method];
    }
    if (current === original)
      return;
    current = original;
    Object.setPrototypeOf(wrapper, inherited || Function);
  }
}

// main.ts
var CONFIG = {
  /** 인라인 제목 변경 시 파일명 반영 대기 시간 */
  TITLE_RENAME_DEBOUNCE_MS: 300,
  /** Daily Note 파일명 패턴 */
  DAILY_NOTE_PATTERN: /^\d{4}-\d{2}-\d{2}\.md$/,
  /** CSS 클래스명 */
  CSS_CLASSES: {
    PREVIEW_TAB: "is-preview-tab",
    ACTIVE: "is-active",
    HAS_FOCUS: "has-focus"
  },
  /** 로그 프리픽스 */
  LOG_PREFIX: "[IDE Preview]"
};
function log(message, ...args) {
  console.log(`${CONFIG.LOG_PREFIX} ${message}`, ...args);
}
var IDEStylePreviewPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    // ─────────────────────────────────────────────────────────────────────────
    // 상태
    // ─────────────────────────────────────────────────────────────────────────
    /** Preview 상태인 탭들 */
    this.previewLeaves = /* @__PURE__ */ new WeakSet();
    /** openFile에서 이미 처리한 탭 (setViewState 중복 방지) */
    this.processedByOpenFile = /* @__PURE__ */ new WeakSet();
    /** Ctrl+Click 감지 플래그 */
    this.isCtrlClickPending = false;
    /** 리본 버튼 더블클릭 시 기대하는 뷰 타입 (null이면 비활성) */
    this.ribbonDoubleClickExpectedViewType = null;
    /** 그래프 뷰 드래그 감지용 */
    this.graphDragStartPos = null;
    /** 새로 생성된 파일들 (제목편집모드 통일용) */
    this.newlyCreatedFiles = /* @__PURE__ */ new Set();
    /** 가장 최근에 열린 leaf */
    this.lastActiveLeaf = null;
    /** 제목 변경 debounce 타이머 */
    this.titleRenameTimer = null;
    /** 패치 해제 함수들 */
    this.cleanupFunctions = [];
  }
  // ─────────────────────────────────────────────────────────────────────────
  // 라이프사이클
  // ─────────────────────────────────────────────────────────────────────────
  async onload() {
    log("Plugin loaded");
    this.installPatches();
    this.registerEventHandlers();
  }
  onunload() {
    this.cleanupFunctions.forEach((cleanup) => cleanup());
    this.cleanupFunctions = [];
    this.removeAllPreviewStyles();
    log("Plugin unloaded");
  }
  installPatches() {
    this.patchOpenFile();
    this.patchSetViewState();
    this.patchDetach();
    this.patchSetPinned();
    this.patchVaultCreate();
  }
  registerEventHandlers() {
    this.registerFileOpenHandler();
    this.registerClickHandlers();
    this.registerPromotionTriggers();
  }
  // ─────────────────────────────────────────────────────────────────────────
  // 디버깅: File Explorer 상태 출력
  // ─────────────────────────────────────────────────────────────────────────
  /**
   * File Explorer의 내부 상태와 DOM 상태를 상세히 출력
   */
  debugFileExplorerState(context) {
    var _a, _b, _c, _d;
    console.log(`
${"=".repeat(60)}`);
    console.log(`${CONFIG.LOG_PREFIX} DEBUG: ${context}`);
    console.log(`${"=".repeat(60)}`);
    const explorerLeaves = this.app.workspace.getLeavesOfType("file-explorer");
    const explorerView = (_a = explorerLeaves[0]) == null ? void 0 : _a.view;
    console.log("1. File Explorer View \uC874\uC7AC:", !!explorerView);
    if (explorerView) {
      const activeDom = explorerView.activeDom;
      console.log("2. activeDom:", activeDom);
      console.log("   activeDom.file:", activeDom == null ? void 0 : activeDom.file);
      console.log("   activeDom.file?.path:", (_b = activeDom == null ? void 0 : activeDom.file) == null ? void 0 : _b.path);
      console.log("   activeDom.el:", activeDom == null ? void 0 : activeDom.el);
      console.log("   activeDom.selfEl:", activeDom == null ? void 0 : activeDom.selfEl);
      const focusedItem = explorerView.focusedItem;
      console.log("3. focusedItem:", focusedItem);
      console.log("   focusedItem?.file?.path:", (_c = focusedItem == null ? void 0 : focusedItem.file) == null ? void 0 : _c.path);
    }
    const activeItems = document.querySelectorAll(".nav-file-title.is-active, .tree-item-self.is-active");
    console.log("4. DOM\uC5D0\uC11C is-active \uD074\uB798\uC2A4 \uAC1C\uC218:", activeItems.length);
    activeItems.forEach((item, idx) => {
      var _a2;
      const path = item.getAttribute("data-path") || ((_a2 = item.closest("[data-path]")) == null ? void 0 : _a2.getAttribute("data-path"));
      console.log(`   [${idx}] path: ${path}`);
      console.log(`   [${idx}] classList:`, Array.from(item.classList));
    });
    const focusedItems = document.querySelectorAll(".nav-file-title.has-focus, .tree-item-self.has-focus");
    console.log("5. DOM\uC5D0\uC11C has-focus \uD074\uB798\uC2A4 \uAC1C\uC218:", focusedItems.length);
    focusedItems.forEach((item, idx) => {
      var _a2;
      const path = item.getAttribute("data-path") || ((_a2 = item.closest("[data-path]")) == null ? void 0 : _a2.getAttribute("data-path"));
      console.log(`   [${idx}] path: ${path}`);
      console.log(`   [${idx}] classList:`, Array.from(item.classList));
    });
    const activeLeaf = this.getActiveLeaf();
    console.log("6. \uD604\uC7AC \uD65C\uC131 Leaf:", activeLeaf ? this.getLeafDebugId(activeLeaf) : "null");
    console.log("   viewType:", (_d = activeLeaf == null ? void 0 : activeLeaf.view) == null ? void 0 : _d.getViewType());
    console.log("   filePath:", activeLeaf ? this.getFilePath(activeLeaf) : "null");
    console.log("   isPreview:", activeLeaf ? this.previewLeaves.has(activeLeaf) : false);
    console.log("7. \uC5F4\uB9B0 \uBAA8\uB4E0 \uD0ED:");
    let tabIndex = 0;
    this.app.workspace.iterateAllLeaves((leaf) => {
      var _a2;
      const location = this.getLeafLocation(leaf);
      if (location === "main") {
        const filePath = this.getFilePath(leaf);
        const viewType = (_a2 = leaf.view) == null ? void 0 : _a2.getViewType();
        const isPreview = this.previewLeaves.has(leaf);
        console.log(`   [${tabIndex}] id: ${this.getLeafDebugId(leaf)}, type: ${viewType}, path: ${filePath}, preview: ${isPreview}`);
        tabIndex++;
      }
    });
    console.log(`${"=".repeat(60)}
`);
  }
  // ─────────────────────────────────────────────────────────────────────────
  // 탭 상태 관리
  // ─────────────────────────────────────────────────────────────────────────
  getTabState(leaf) {
    var _a;
    if (((_a = leaf.view) == null ? void 0 : _a.getViewType()) === "empty")
      return "empty";
    if (this.previewLeaves.has(leaf))
      return "preview";
    return "permanent";
  }
  setAsPreview(leaf) {
    this.previewLeaves.add(leaf);
    this.updateTabStyle(leaf);
  }
  setAsPermanent(leaf) {
    this.previewLeaves.delete(leaf);
    this.updateTabStyle(leaf);
  }
  promoteToPermament(leaf) {
    if (!this.previewLeaves.has(leaf))
      return;
    this.setAsPermanent(leaf);
    log("Promoted to permanent:", this.getLeafDebugId(leaf));
  }
  // ─────────────────────────────────────────────────────────────────────────
  // 위치 판단 (사용자 멘탈 모델 기반)
  // ─────────────────────────────────────────────────────────────────────────
  /**
   * Leaf가 사이드바에 있는지 판단
   * - 사용자 관점: "왼쪽/오른쪽 패널"
   * - 구현 세부사항(file-explorer, bookmarks 등)에 의존하지 않음
   */
  getLeafLocation(leaf) {
    const workspace = this.app.workspace;
    const root = leaf.getRoot();
    if (root === workspace.leftSplit || root === workspace.rightSplit) {
      return "sidebar";
    }
    return "main";
  }
  isInSidebar(leaf) {
    return this.getLeafLocation(leaf) === "sidebar";
  }
  // ─────────────────────────────────────────────────────────────────────────
  // 의도 판별
  // ─────────────────────────────────────────────────────────────────────────
  /**
   * 파일 열기 의도 판별
   * - create: 새 노트 생성, Daily Note 등 → Permanent
   * - browse: 탐색 목적 → Preview
   */
  determineOpenIntent(file, openState) {
    var _a, _b;
    if (((_a = openState == null ? void 0 : openState.eState) == null ? void 0 : _a.rename) === "all") {
      return "create";
    }
    if (((_b = openState == null ? void 0 : openState.state) == null ? void 0 : _b.mode) === "source") {
      if (CONFIG.DAILY_NOTE_PATTERN.test(file.name)) {
        return "create";
      }
    }
    return "browse";
  }
  // ─────────────────────────────────────────────────────────────────────────
  // Leaf 탐색
  // ─────────────────────────────────────────────────────────────────────────
  /**
   * 같은 탭 그룹 내에서 특정 파일이 열린 탭 찾기
   */
  findLeafWithFile(filePath, inSameGroupAs) {
    const siblings = this.getSiblingLeaves(inSameGroupAs);
    for (const sibling of siblings) {
      if (this.getFilePath(sibling) === filePath) {
        return sibling;
      }
    }
    return null;
  }
  /**
   * 같은 탭 그룹 내에서 특정 뷰 타입이 열린 탭 찾기
   */
  findLeafWithViewType(viewType, inSameGroupAs) {
    var _a;
    const siblings = this.getSiblingLeaves(inSameGroupAs);
    for (const sibling of siblings) {
      if (((_a = sibling.view) == null ? void 0 : _a.getViewType()) === viewType) {
        return sibling;
      }
    }
    return null;
  }
  /**
   * 같은 탭 그룹 내에서 Preview 탭 찾기
   */
  findPreviewLeaf(inSameGroupAs) {
    const siblings = this.getSiblingLeaves(inSameGroupAs);
    for (const sibling of siblings) {
      if (this.previewLeaves.has(sibling)) {
        return sibling;
      }
    }
    return null;
  }
  /**
   * 같은 탭 그룹의 형제 탭들 가져오기
   */
  getSiblingLeaves(leaf) {
    var _a;
    const internal = leaf;
    const children = (_a = internal.parent) == null ? void 0 : _a.children;
    if (!children)
      return [];
    return children.filter((child) => child !== leaf);
  }
  isFileOpenInAnyLeaf(filePath, excludeLeaf) {
    let found = false;
    this.app.workspace.iterateAllLeaves((leaf) => {
      if (found)
        return;
      if (excludeLeaf && leaf === excludeLeaf)
        return;
      if (this.getFilePath(leaf) === filePath) {
        found = true;
      }
    });
    return found;
  }
  // ─────────────────────────────────────────────────────────────────────────
  // openFile 패치
  // ─────────────────────────────────────────────────────────────────────────
  patchOpenFile() {
    const plugin = this;
    const uninstall = around(import_obsidian.WorkspaceLeaf.prototype, {
      openFile(original) {
        return async function(file, openState) {
          return plugin.handleOpenFile(this, file, openState, original);
        };
      }
    });
    this.cleanupFunctions.push(uninstall);
    log("Patched openFile");
  }
  async handleOpenFile(leaf, file, openState, originalMethod) {
    console.log(`
${"-".repeat(40)}`);
    console.log(`${CONFIG.LOG_PREFIX} handleOpenFile \uC9C4\uC785`);
    console.log(`  file.path: ${file.path}`);
    console.log(`  leaf.id: ${this.getLeafDebugId(leaf)}`);
    this.debugFileExplorerState("handleOpenFile \uC9C4\uC785 \uC2DC\uC810");
    if (this.newlyCreatedFiles.has(file.path)) {
      this.newlyCreatedFiles.delete(file.path);
      openState = openState || {};
      openState.eState = openState.eState || {};
      openState.eState.rename = "all";
    }
    const currentState = this.getTabState(leaf);
    const intent = this.determineOpenIntent(file, openState);
    const isCtrlClick = this.consumeCtrlClickFlag();
    const shouldBePermanent = intent === "create" || isCtrlClick;
    log(`openFile: ${file.path}`);
    log(`  state=${currentState}, intent=${intent}, permanent=${shouldBePermanent}`);
    if (this.getFilePath(leaf) === file.path) {
      log("  \u2192 Same file, skipping");
      return;
    }
    const existingLeaf = this.findLeafWithFile(file.path, leaf);
    if (existingLeaf && intent === "browse" && !isCtrlClick) {
      log("  \u2192 Already open, focusing existing tab");
      this.app.workspace.setActiveLeaf(existingLeaf, { focus: true });
      return;
    }
    if (shouldBePermanent) {
      if (currentState === "permanent" || currentState === "preview") {
        const result3 = await this.openInNewTab(leaf, file, openState, true, originalMethod);
        this.debugFileExplorerState("openInNewTab (permanent) \uC644\uB8CC \uD6C4");
        return result3;
      }
      this.markAsProcessed(leaf);
      const result2 = await originalMethod.call(leaf, file, openState);
      this.setAsPermanent(leaf);
      this.debugFileExplorerState("Empty \u2192 Permanent \uC644\uB8CC \uD6C4");
      return result2;
    }
    const existingPreview = this.findPreviewLeaf(leaf);
    if (existingPreview) {
      log("  \u2192 Reusing existing preview tab");
      this.markAsProcessed(existingPreview);
      const result2 = await originalMethod.call(existingPreview, file, openState);
      this.app.workspace.setActiveLeaf(existingPreview, { focus: true });
      this.debugFileExplorerState("Preview \uC7AC\uC0AC\uC6A9 \uC644\uB8CC \uD6C4");
      return result2;
    }
    if (currentState === "permanent") {
      const result2 = await this.openInNewTab(leaf, file, openState, false, originalMethod);
      this.debugFileExplorerState("openInNewTab (preview) \uC644\uB8CC \uD6C4");
      return result2;
    }
    this.markAsProcessed(leaf);
    const result = await originalMethod.call(leaf, file, openState);
    this.setAsPreview(leaf);
    this.debugFileExplorerState("Empty/Preview \u2192 Preview \uC644\uB8CC \uD6C4");
    return result;
  }
  async openInNewTab(_fromLeaf, file, openState, asPermanent, originalMethod) {
    var _a;
    const shouldApplyRename = ((_a = openState == null ? void 0 : openState.eState) == null ? void 0 : _a.rename) === "all";
    const newLeaf = this.app.workspace.getLeaf("tab");
    this.markAsProcessed(newLeaf);
    const result = await originalMethod.call(newLeaf, file, openState);
    if (asPermanent) {
      this.setAsPermanent(newLeaf);
    } else {
      this.setAsPreview(newLeaf);
    }
    this.app.workspace.setActiveLeaf(newLeaf, { focus: true });
    if (shouldApplyRename) {
      this.applyRenameMode(newLeaf);
    }
    return result;
  }
  /**
   * 제목편집모드 수동 적용
   * - 새 탭에서 파일을 열 때 eState.rename이 무시되는 문제 해결
   */
  applyRenameMode(leaf) {
    const view = leaf.view;
    if (view == null ? void 0 : view.setEphemeralState) {
      view.setEphemeralState({ rename: "all" });
    }
  }
  // ─────────────────────────────────────────────────────────────────────────
  // setViewState 패치 (비파일 뷰 처리)
  // ─────────────────────────────────────────────────────────────────────────
  patchSetViewState() {
    const plugin = this;
    const uninstall = around(import_obsidian.WorkspaceLeaf.prototype, {
      setViewState(original) {
        return async function(viewState, eState) {
          return plugin.handleSetViewState(this, viewState, eState, original);
        };
      }
    });
    this.cleanupFunctions.push(uninstall);
    log("Patched setViewState");
  }
  async handleSetViewState(leaf, viewState, eState, originalMethod) {
    var _a;
    if (this.wasProcessed(leaf)) {
      this.clearProcessed(leaf);
      return originalMethod.call(leaf, viewState, eState);
    }
    const viewType = viewState == null ? void 0 : viewState.type;
    if (viewType === "markdown" || viewType === "empty") {
      return originalMethod.call(leaf, viewState, eState);
    }
    if (this.isInSidebar(leaf)) {
      return originalMethod.call(leaf, viewState, eState);
    }
    const currentState = this.getTabState(leaf);
    const shouldBePermanent = this.consumeRibbonDoubleClickFlag(viewType);
    const leafId = this.getLeafDebugId(leaf);
    log(`setViewState: type=${viewType}, state=${currentState}, permanent=${shouldBePermanent}, leafId=${leafId}`);
    if (((_a = leaf.view) == null ? void 0 : _a.getViewType()) === viewType) {
      if (shouldBePermanent && this.previewLeaves.has(leaf)) {
        log(`  \u2192 Same view type, promoting to permanent`);
        this.promoteToPermament(leaf);
      } else {
        log(`  \u2192 Same view type, skipping`);
      }
      return;
    }
    const existingLeaf = this.findLeafWithViewType(viewType, leaf);
    if (existingLeaf) {
      log(`  \u2192 Already open: ${viewType}, focusing existing tab`);
      if (shouldBePermanent && this.previewLeaves.has(existingLeaf)) {
        this.promoteToPermament(existingLeaf);
      }
      this.app.workspace.setActiveLeaf(existingLeaf, { focus: true });
      return;
    }
    if (shouldBePermanent) {
      if (currentState === "permanent" || currentState === "preview") {
        const newLeaf = this.app.workspace.getLeaf("tab");
        const result3 = await originalMethod.call(newLeaf, viewState, eState);
        this.setAsPermanent(newLeaf);
        this.app.workspace.setActiveLeaf(newLeaf, { focus: true });
        return result3;
      }
      const result2 = await originalMethod.call(leaf, viewState, eState);
      this.setAsPermanent(leaf);
      return result2;
    }
    const existingPreview = this.findPreviewLeaf(leaf);
    if (existingPreview) {
      const previewId = this.getLeafDebugId(existingPreview);
      log(`  \u2192 Reusing existing preview tab (leafId=${previewId})`);
      const result2 = await originalMethod.call(existingPreview, viewState, eState);
      log(`  \u2192 After setViewState, isPreview=${this.previewLeaves.has(existingPreview)}`);
      this.app.workspace.setActiveLeaf(existingPreview, { focus: true });
      return result2;
    }
    if (currentState === "permanent") {
      const newLeaf = this.app.workspace.getLeaf("tab");
      const newLeafId = this.getLeafDebugId(newLeaf);
      log(`  \u2192 Creating new preview tab (leafId=${newLeafId})`);
      const result2 = await originalMethod.call(newLeaf, viewState, eState);
      this.setAsPreview(newLeaf);
      log(`  \u2192 After setAsPreview, isPreview=${this.previewLeaves.has(newLeaf)}`);
      this.app.workspace.setActiveLeaf(newLeaf, { focus: true });
      return result2;
    }
    log(`  \u2192 Using current tab (leafId=${leafId})`);
    const result = await originalMethod.call(leaf, viewState, eState);
    this.setAsPreview(leaf);
    log(`  \u2192 After setAsPreview, isPreview=${this.previewLeaves.has(leaf)}`);
    return result;
  }
  // ─────────────────────────────────────────────────────────────────────────
  // detach 패치 (탭 닫힘 처리)
  // ─────────────────────────────────────────────────────────────────────────
  patchDetach() {
    const plugin = this;
    const uninstall = around(import_obsidian.WorkspaceLeaf.prototype, {
      detach(original) {
        return function() {
          const filePath = plugin.getFilePath(this);
          const leafId = plugin.getLeafDebugId(this);
          console.log(`
${"-".repeat(40)}`);
          console.log(`${CONFIG.LOG_PREFIX} detach \uC9C4\uC785`);
          console.log(`  \uB2EB\uD788\uB294 \uD0ED leaf.id: ${leafId}`);
          console.log(`  \uB2EB\uD788\uB294 \uD0ED filePath: ${filePath}`);
          plugin.debugFileExplorerState("detach \uC9C4\uC785 \uC2DC\uC810 (clearAllSidebarSelections \uD638\uCD9C \uC804)");
          plugin.clearAllSidebarSelections();
          plugin.debugFileExplorerState("clearAllSidebarSelections \uD638\uCD9C \uD6C4");
          const result = original.call(this);
          plugin.debugFileExplorerState("original detach \uC644\uB8CC \uD6C4");
          return result;
        };
      }
    });
    this.cleanupFunctions.push(uninstall);
    log("Patched detach");
  }
  // ─────────────────────────────────────────────────────────────────────────
  // setPinned 패치 (탭 고정 시 승격)
  // ─────────────────────────────────────────────────────────────────────────
  patchSetPinned() {
    const plugin = this;
    const uninstall = around(import_obsidian.WorkspaceLeaf.prototype, {
      setPinned(original) {
        return function(pinned) {
          if (pinned && plugin.previewLeaves.has(this)) {
            log("Tab pinned \u2192 promote");
            plugin.promoteToPermament(this);
          }
          return original.call(this, pinned);
        };
      }
    });
    this.cleanupFunctions.push(uninstall);
    log("Patched setPinned");
  }
  // ─────────────────────────────────────────────────────────────────────────
  // vault.create 패치 (새 파일 생성 감지)
  // ─────────────────────────────────────────────────────────────────────────
  patchVaultCreate() {
    const plugin = this;
    const vault = this.app.vault;
    const originalCreate = vault.create.bind(vault);
    vault.create = async function(path, data, options) {
      plugin.newlyCreatedFiles.add(path);
      return originalCreate(path, data, options);
    };
    this.cleanupFunctions.push(() => {
      vault.create = originalCreate;
    });
    log("Patched vault.create");
  }
  // ─────────────────────────────────────────────────────────────────────────
  // 이벤트 핸들러
  // ─────────────────────────────────────────────────────────────────────────
  registerFileOpenHandler() {
    this.registerEvent(
      this.app.workspace.on("file-open", (file) => {
        var _a, _b;
        console.log(`
${"-".repeat(40)}`);
        console.log(`${CONFIG.LOG_PREFIX} file-open \uC774\uBCA4\uD2B8`);
        console.log(`  file: ${(_a = file == null ? void 0 : file.path) != null ? _a : "null"}`);
        this.debugFileExplorerState("file-open \uC774\uBCA4\uD2B8 \uBC1C\uC0DD");
        if (!file)
          return;
        const activeLeaf = this.getActiveLeaf();
        if (((_b = activeLeaf == null ? void 0 : activeLeaf.view) == null ? void 0 : _b.getViewType()) === "markdown") {
          this.lastActiveLeaf = activeLeaf;
        }
      })
    );
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", (leaf) => {
        var _a;
        if (!this.ribbonDoubleClickExpectedViewType || !leaf) {
          return;
        }
        const viewType = (_a = leaf.view) == null ? void 0 : _a.getViewType();
        const expectedType = this.ribbonDoubleClickExpectedViewType;
        if (viewType === expectedType && this.previewLeaves.has(leaf)) {
          log(`Active leaf change \u2192 promoting expected ${viewType} view`);
          this.promoteToPermament(leaf);
        }
        this.ribbonDoubleClickExpectedViewType = null;
      })
    );
  }
  registerClickHandlers() {
    this.registerDomEvent(document, "click", (evt) => {
      const target = evt.target;
      const fileEl = target.closest("[data-path]");
      if (fileEl) {
        const path = fileEl.getAttribute("data-path");
        console.log(`
${"-".repeat(40)}`);
        console.log(`${CONFIG.LOG_PREFIX} \uD30C\uC77C \uC694\uC18C \uD074\uB9AD`);
        console.log(`  \uD074\uB9AD\uB41C \uD30C\uC77C path: ${path}`);
        console.log(`  Ctrl/Meta \uD0A4: ${evt.ctrlKey || evt.metaKey}`);
        this.debugFileExplorerState("\uD30C\uC77C \uC694\uC18C \uD074\uB9AD \uC2DC\uC810");
      }
      if ((evt.ctrlKey || evt.metaKey) && this.isFileElement(evt.target)) {
        this.isCtrlClickPending = true;
      }
    }, true);
    this.registerDomEvent(document, "dblclick", (evt) => {
      const target = evt.target;
      const fileEl = target.closest("[data-path]");
      if (fileEl) {
        const path = fileEl.getAttribute("data-path");
        console.log(`
${"-".repeat(40)}`);
        console.log(`${CONFIG.LOG_PREFIX} \uD30C\uC77C \uC694\uC18C \uB354\uBE14\uD074\uB9AD`);
        console.log(`  \uB354\uBE14\uD074\uB9AD\uB41C \uD30C\uC77C path: ${path}`);
        this.debugFileExplorerState("\uD30C\uC77C \uC694\uC18C \uB354\uBE14\uD074\uB9AD \uC2DC\uC810");
      }
      this.handleDoubleClick(evt);
    }, true);
    this.registerDomEvent(document, "mousedown", (evt) => {
      var _a;
      const target = evt.target;
      const activeLeaf = this.getActiveLeaf();
      const viewType = (_a = activeLeaf == null ? void 0 : activeLeaf.view) == null ? void 0 : _a.getViewType();
      if (viewType === "graph") {
        const leafId = activeLeaf ? this.getLeafDebugId(activeLeaf) : "null";
        console.log("[IDE Preview] mousedown debug:");
        console.log("  leafId:", leafId);
        console.log("  target.tagName:", target.tagName);
        console.log("  activeLeaf viewType:", viewType);
        console.log("  isPreview:", activeLeaf ? this.previewLeaves.has(activeLeaf) : false);
      }
      if (viewType === "graph") {
        this.graphDragStartPos = { x: evt.clientX, y: evt.clientY };
        console.log("[IDE Preview] graphDragStartPos set:", this.graphDragStartPos);
      }
    }, true);
    this.registerDomEvent(document, "mouseup", (evt) => {
      var _a;
      if (!this.graphDragStartPos)
        return;
      const activeLeaf = this.getActiveLeaf();
      const viewType = (_a = activeLeaf == null ? void 0 : activeLeaf.view) == null ? void 0 : _a.getViewType();
      const leafId = activeLeaf ? this.getLeafDebugId(activeLeaf) : "null";
      console.log("[IDE Preview] mouseup debug:");
      console.log("  leafId:", leafId);
      console.log("  viewType:", viewType);
      if (viewType === "graph") {
        const dx = evt.clientX - this.graphDragStartPos.x;
        const dy = evt.clientY - this.graphDragStartPos.y;
        const distance = Math.sqrt(dx * dx + dy * dy);
        console.log("  drag distance:", distance);
        console.log("  isPreview:", activeLeaf ? this.previewLeaves.has(activeLeaf) : false);
        if (distance > 10) {
          if (activeLeaf && this.previewLeaves.has(activeLeaf)) {
            log("Graph drag detected \u2192 promote");
            this.promoteToPermament(activeLeaf);
          }
        }
      }
      this.graphDragStartPos = null;
    }, true);
  }
  handleDoubleClick(evt) {
    var _a, _b, _c;
    const target = evt.target;
    if (target.closest(".workspace-tab-header")) {
      const activeLeaf = this.getActiveLeaf();
      if (activeLeaf && this.previewLeaves.has(activeLeaf)) {
        log("Tab header double-click \u2192 promote");
        this.promoteToPermament(activeLeaf);
      }
      return;
    }
    const sidebarContent = target.closest(".workspace-leaf-content");
    if (sidebarContent) {
      const leaf = this.findLeafByContentEl(sidebarContent);
      if (leaf && this.isInSidebar(leaf)) {
        if (this.lastActiveLeaf && this.previewLeaves.has(this.lastActiveLeaf)) {
          log("Sidebar double-click \u2192 promote");
          this.promoteToPermament(this.lastActiveLeaf);
        }
        return;
      }
    }
    if (target.closest(".graph-view-container")) {
      if (this.lastActiveLeaf && this.previewLeaves.has(this.lastActiveLeaf)) {
        log("Graph double-click \u2192 promote");
        this.promoteToPermament(this.lastActiveLeaf);
      }
      return;
    }
    const ribbonButton = target.closest(".side-dock-ribbon-action");
    if (ribbonButton) {
      const ariaLabel = (_a = ribbonButton.getAttribute("aria-label")) != null ? _a : "";
      const activeLeaf = this.getActiveLeaf();
      const activeViewType = (_b = activeLeaf == null ? void 0 : activeLeaf.view) == null ? void 0 : _b.getViewType();
      log("Ribbon button double-click");
      log(`  aria-label: "${ariaLabel}"`);
      log(`  activeLeaf viewType: ${activeViewType}`);
      log(`  isPreview: ${activeLeaf ? this.previewLeaves.has(activeLeaf) : false}`);
      if (activeLeaf && this.previewLeaves.has(activeLeaf)) {
        log(`  \u2192 Promoting active preview tab`);
        this.promoteToPermament(activeLeaf);
        return;
      }
      const ariaLower = ariaLabel.toLowerCase();
      let viewType = null;
      if (ariaLower.includes("graph") || ariaLabel.includes("\uADF8\uB798\uD504")) {
        viewType = "graph";
      } else if (ariaLower.includes("canvas") || ariaLabel.includes("\uCE94\uBC84\uC2A4")) {
        viewType = "canvas";
      }
      if (viewType) {
        const activeLeaf2 = this.getActiveLeaf();
        if (((_c = activeLeaf2 == null ? void 0 : activeLeaf2.view) == null ? void 0 : _c.getViewType()) === viewType && this.previewLeaves.has(activeLeaf2)) {
          log(`  \u2192 Promoting existing ${viewType} view`);
          this.promoteToPermament(activeLeaf2);
          return;
        }
      }
      if (viewType) {
        this.ribbonDoubleClickExpectedViewType = viewType;
        log(`  \u2192 Expecting ${viewType} view on next active-leaf-change`);
      }
    }
  }
  registerPromotionTriggers() {
    this.registerEvent(
      this.app.workspace.on("editor-change", (editor, info) => {
        const leaf = info.leaf;
        if (leaf && this.previewLeaves.has(leaf)) {
          log("Editor change \u2192 promote");
          this.promoteToPermament(leaf);
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("rename", (file, oldPath) => {
        this.app.workspace.iterateAllLeaves((leaf) => {
          if (this.getFilePath(leaf) === file.path && this.previewLeaves.has(leaf)) {
            log("File renamed \u2192 promote");
            this.promoteToPermament(leaf);
          }
        });
      })
    );
    this.registerDomEvent(document, "input", (evt) => {
      this.handleInlineTitleEdit(evt);
    }, true);
  }
  handleInlineTitleEdit(evt) {
    var _a, _b;
    const target = evt.target;
    if (!target.classList.contains("inline-title"))
      return;
    const activeLeaf = this.getActiveLeaf();
    if (!activeLeaf)
      return;
    if (this.previewLeaves.has(activeLeaf)) {
      log("Inline title edit \u2192 promote");
      this.promoteToPermament(activeLeaf);
    }
    this.scheduleFileRename(activeLeaf, (_b = (_a = target.textContent) == null ? void 0 : _a.trim()) != null ? _b : "");
  }
  scheduleFileRename(leaf, newTitle) {
    const currentPath = this.getFilePath(leaf);
    if (!currentPath || !newTitle)
      return;
    if (this.titleRenameTimer) {
      window.clearTimeout(this.titleRenameTimer);
    }
    this.titleRenameTimer = window.setTimeout(async () => {
      await this.renameFile(currentPath, newTitle);
    }, CONFIG.TITLE_RENAME_DEBOUNCE_MS);
  }
  async renameFile(currentPath, newTitle) {
    var _a, _b;
    const file = this.app.vault.getAbstractFileByPath(currentPath);
    if (!(file instanceof import_obsidian.TFile))
      return;
    const folder = (_b = (_a = file.parent) == null ? void 0 : _a.path) != null ? _b : "";
    const newPath = folder ? `${folder}/${newTitle}.md` : `${newTitle}.md`;
    if (newPath === currentPath)
      return;
    try {
      log(`Renaming: ${currentPath} \u2192 ${newPath}`);
      await this.app.fileManager.renameFile(file, newPath);
    } catch (e) {
      const message = e instanceof Error ? e.message : String(e);
      log(`Rename failed: ${message}`);
      new import_obsidian.Notice(`\uD30C\uC77C\uBA85 \uBCC0\uACBD \uC2E4\uD328: ${message}`);
    }
  }
  // ─────────────────────────────────────────────────────────────────────────
  // 스타일 관리
  // ─────────────────────────────────────────────────────────────────────────
  updateTabStyle(leaf) {
    const tabHeaderEl = leaf.tabHeaderEl;
    if (!tabHeaderEl)
      return;
    if (this.previewLeaves.has(leaf)) {
      tabHeaderEl.classList.add(CONFIG.CSS_CLASSES.PREVIEW_TAB);
    } else {
      tabHeaderEl.classList.remove(CONFIG.CSS_CLASSES.PREVIEW_TAB);
    }
  }
  removeAllPreviewStyles() {
    this.app.workspace.iterateAllLeaves((leaf) => {
      const tabHeaderEl = leaf.tabHeaderEl;
      tabHeaderEl == null ? void 0 : tabHeaderEl.classList.remove(CONFIG.CSS_CLASSES.PREVIEW_TAB);
    });
  }
  // ─────────────────────────────────────────────────────────────────────────
  // 사이드바 선택 상태 정리
  // ─────────────────────────────────────────────────────────────────────────
  /**
   * 사이드바의 모든 파일 선택 상태 해제 (SPEC 7.5)
   * - 탭이 닫힐 때 호출
   * - DOM 클래스만 제거
   */
  clearAllSidebarSelections() {
    var _a, _b, _c;
    log("=== clearAllSidebarSelections ===");
    const explorerLeaves = this.app.workspace.getLeavesOfType("file-explorer");
    const explorerView = (_a = explorerLeaves[0]) == null ? void 0 : _a.view;
    if (explorerView) {
      console.log("  clearAllSidebarSelections \uB0B4\uBD80:");
      console.log("    explorerView.activeDom:", explorerView.activeDom);
      console.log("    explorerView.activeDom?.file?.path:", (_c = (_b = explorerView.activeDom) == null ? void 0 : _b.file) == null ? void 0 : _c.path);
    }
    const sidebars = document.querySelectorAll(
      ".workspace-split.mod-left-split, .workspace-split.mod-right-split"
    );
    sidebars.forEach((sidebar) => {
      const activeItems = sidebar.querySelectorAll(
        ".tree-item-self.is-active, .tree-item-self.has-focus"
      );
      console.log(`    sidebar\uC5D0\uC11C \uCC3E\uC740 active/focus \uC694\uC18C \uC218: ${activeItems.length}`);
      activeItems.forEach((item) => {
        var _a2;
        const path = (_a2 = item.closest("[data-path]")) == null ? void 0 : _a2.getAttribute("data-path");
        console.log(`      \uC81C\uAC70 \uB300\uC0C1: ${path}`);
        item.classList.remove("is-active");
        item.classList.remove("has-focus");
      });
    });
  }
  // ─────────────────────────────────────────────────────────────────────────
  // 유틸리티
  // ─────────────────────────────────────────────────────────────────────────
  getFilePath(leaf) {
    const view = leaf.view;
    if (view instanceof import_obsidian.FileView && view.file) {
      return view.file.path;
    }
    return null;
  }
  getLeafDebugId(leaf) {
    var _a;
    return (_a = leaf.id) != null ? _a : "unknown";
  }
  /** activeLeaf의 대체 (deprecated 회피) */
  getActiveLeaf() {
    return this.app.workspace.getMostRecentLeaf();
  }
  isFileElement(target) {
    if (!(target instanceof HTMLElement))
      return false;
    return !!target.closest("[data-path]");
  }
  findLeafByContentEl(contentEl) {
    let found = null;
    this.app.workspace.iterateAllLeaves((leaf) => {
      var _a;
      if ((_a = leaf.containerEl) == null ? void 0 : _a.contains(contentEl)) {
        found = leaf;
      }
    });
    return found;
  }
  markAsProcessed(leaf) {
    this.processedByOpenFile.add(leaf);
  }
  wasProcessed(leaf) {
    return this.processedByOpenFile.has(leaf);
  }
  clearProcessed(leaf) {
    this.processedByOpenFile.delete(leaf);
  }
  consumeCtrlClickFlag() {
    if (this.isCtrlClickPending) {
      this.isCtrlClickPending = false;
      return true;
    }
    return false;
  }
  consumeRibbonDoubleClickFlag(viewType) {
    if (this.ribbonDoubleClickExpectedViewType === viewType) {
      this.ribbonDoubleClickExpectedViewType = null;
      return true;
    }
    return false;
  }
};
