/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => PreviewModePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  useItalicTitle: true,
  reuseEmptyTab: true,
  promoteOldPreview: true,
  jumpToDuplicate: true
};
var PREVIEW_CLASS = "is-preview-tab";
var PreviewModePlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.previewLeaf = null;
    // [수정 2] 화살표 함수로 변경하여 'this' 스코프 문제 해결
    this.handleClick = (evt) => {
      const target = evt.target;
      const titleEl = target.closest(".nav-file-title");
      if (!titleEl)
        return;
      if (evt.ctrlKey || evt.metaKey || evt.shiftKey)
        return;
      const path = titleEl.getAttribute("data-path");
      if (!path)
        return;
      const file = this.app.vault.getAbstractFileByPath(path);
      if (!(file instanceof import_obsidian.TFile))
        return;
      evt.preventDefault();
      evt.stopPropagation();
      evt.stopImmediatePropagation();
      void this.openFileLogic(file, false);
    };
    // [수정 2] 화살표 함수로 변경
    this.handleDblClick = (evt) => {
      const target = evt.target;
      const titleEl = target.closest(".nav-file-title");
      if (!titleEl)
        return;
      const path = titleEl.getAttribute("data-path");
      if (!path)
        return;
      const file = this.app.vault.getAbstractFileByPath(path);
      if (!(file instanceof import_obsidian.TFile))
        return;
      evt.preventDefault();
      evt.stopPropagation();
      evt.stopImmediatePropagation();
      void this.openFileLogic(file, true);
    };
    // [수정 2] 화살표 함수로 변경
    this.handleHeaderDblClick = (evt) => {
      const target = evt.target;
      const tabHeader = target.closest(".workspace-tab-header");
      if (tabHeader && this.previewLeaf && this.previewLeaf.tabHeaderEl === tabHeader) {
        evt.preventDefault();
        evt.stopPropagation();
        evt.stopImmediatePropagation();
        this.markAsPermanent(this.previewLeaf);
      }
    };
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new PreviewModeSettingTab(this.app, this));
    document.addEventListener("click", this.handleClick, true);
    document.addEventListener("dblclick", this.handleDblClick, true);
    document.addEventListener("dblclick", this.handleHeaderDblClick, true);
    this.registerEvent(this.app.workspace.on("editor-change", (editor, info) => {
      const activeLeaf = this.app.workspace.getLeaf(false);
      if (this.previewLeaf === activeLeaf) {
        this.markAsPermanent(activeLeaf);
      }
    }));
    this.registerEvent(this.app.workspace.on("layout-change", () => {
      if (this.previewLeaf) {
        const exists = this.app.workspace.getLeafById(this.previewLeaf.id);
        if (!exists) {
          this.previewLeaf = null;
        }
      }
    }));
  }
  onunload() {
    document.removeEventListener("click", this.handleClick, true);
    document.removeEventListener("dblclick", this.handleDblClick, true);
    document.removeEventListener("dblclick", this.handleHeaderDblClick, true);
    document.querySelectorAll(`.${PREVIEW_CLASS}`).forEach((el) => {
      el.classList.remove(PREVIEW_CLASS);
    });
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async openFileLogic(file, isDoubleClick) {
    if (this.settings.jumpToDuplicate) {
      let existingLeaf = null;
      this.app.workspace.iterateAllLeaves((leaf) => {
        if (leaf.view.file && leaf.view.file.path === file.path) {
          existingLeaf = leaf;
        }
      });
      if (existingLeaf) {
        this.app.workspace.setActiveLeaf(existingLeaf, { focus: true });
        if (isDoubleClick)
          this.markAsPermanent(existingLeaf);
        return;
      }
    }
    if (isDoubleClick) {
      if (this.previewLeaf && this.previewLeaf.view.file && this.previewLeaf.view.file.path === file.path) {
        this.markAsPermanent(this.previewLeaf);
      } else {
        const leaf = this.app.workspace.getLeaf("tab");
        await leaf.openFile(file);
        this.markAsPermanent(leaf);
      }
    } else {
      const activeLeaf = this.app.workspace.getLeaf(false);
      const oldPreview = this.previewLeaf;
      let targetLeaf = null;
      const isOldPreviewValid = oldPreview && this.app.workspace.getLeafById(oldPreview.id);
      if (this.settings.reuseEmptyTab && activeLeaf.view.getViewType() === "empty") {
        targetLeaf = activeLeaf;
        if (isOldPreviewValid && oldPreview !== targetLeaf) {
          if (this.settings.promoteOldPreview) {
            this.markAsPermanent(oldPreview);
          } else {
            oldPreview.detach();
          }
        }
      } else if (activeLeaf === oldPreview) {
        targetLeaf = activeLeaf;
      } else {
        if (isOldPreviewValid) {
          targetLeaf = oldPreview;
          this.app.workspace.setActiveLeaf(targetLeaf, { focus: true });
        } else {
          targetLeaf = this.app.workspace.getLeaf("tab");
        }
      }
      await targetLeaf.openFile(file);
      this.markAsPreview(targetLeaf);
    }
  }
  markAsPreview(leaf) {
    this.previewLeaf = leaf;
    if (this.settings.useItalicTitle && leaf.tabHeaderEl) {
      leaf.tabHeaderEl.classList.add(PREVIEW_CLASS);
    }
  }
  markAsPermanent(leaf) {
    if (this.previewLeaf === leaf) {
      this.previewLeaf = null;
    }
    if (leaf.tabHeaderEl) {
      leaf.tabHeaderEl.classList.remove(PREVIEW_CLASS);
    }
  }
};
var PreviewModeSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Italic title for preview").setDesc("Display the preview tab title in italics.").addToggle((toggle) => toggle.setValue(this.plugin.settings.useItalicTitle).onChange(async (value) => {
      this.plugin.settings.useItalicTitle = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Reuse empty tab (locality)").setDesc("If the current tab is empty, open the file in it instead of creating a new one.").addToggle((toggle) => toggle.setValue(this.plugin.settings.reuseEmptyTab).onChange(async (value) => {
      this.plugin.settings.reuseEmptyTab = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Promote old preview").setDesc("If a new preview is opened elsewhere, keep the old preview tab as a regular tab instead of closing it.").addToggle((toggle) => toggle.setValue(this.plugin.settings.promoteOldPreview).onChange(async (value) => {
      this.plugin.settings.promoteOldPreview = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Focus existing tab").setDesc("If the file is already open, jump to that tab instead of opening it again.").addToggle((toggle) => toggle.setValue(this.plugin.settings.jumpToDuplicate).onChange(async (value) => {
      this.plugin.settings.jumpToDuplicate = value;
      await this.plugin.saveSettings();
    }));
  }
};
